[build]
  command   = "echo REACT_APP_API_KEY=$WEATHER_API_KEY > .env && npm run build"
  publish   = "build"

# React SPA: serve index.html for all routes
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
